name: "Deploy Beanstalk application"
author: "Marcel Arns <marcel.arns@moneymeets.com>"
description: "Create Beanstalk application version and update environment"
inputs:
  application_name:
    required: true
    description: "Name of the beanstalk application"
  docker_compose_path:
    required: false
    description: "Path to docker-compose.yml"
    default: "${{ github.workspace }}/docker/docker-compose.yml"
  environment_name:
    required: true
    description: "Beanstalk environment name"
  platform_hooks_path:
    required: false
    description: "Path to hooks directory, which can contain .ebextensions and/or .platform folder"
  region:
    required: true
    description: "Region of the Beanstalk platform"
  version_label:
    required: false
    description: "Version label (default: github.sha)"
    default: ${{ github.sha }}
  version_description:
    required: false
    description: "Version description (default: github.run_number)"
    default: "GitHub Action #${{ github.run_number }}"

runs:
  using: "composite"
  steps:
    - name: Setup Python + Poetry
      uses: moneymeets/action-setup-python-poetry@master

    - name: Run
      run: |
        poetry install --no-dev
        poetry run python action.py
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        APPLICATION_NAME: ${{ inputs.application_name }}
        DOCKER_COMPOSE_PATH: ${{ inputs.docker_compose_path }}
        ENVIRONMENT_NAME: ${{ inputs.environment_name }}
        PLATFORM_HOOKS_PATH: ${{ inputs.platform_hooks_path }}
        REGION: ${{ inputs.region }}
        VERSION_DESCRIPTION: ${{ inputs.version_description }}
        VERSION_LABEL: ${{ inputs.version_label }}

        PYTHONUNBUFFERED: "1"
