name: CI
on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python + Poetry
        uses: moneymeets/action-setup-python-poetry@master

      - name: Run linter
        run: |
          find . -name '*.py' | xargs poetry run add-trailing-comma --py36-plus
          poetry run flake8

      - name: Test
        run: poetry run pytest --cov --cov-branch --cov-fail-under=80
