name: CI
on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1

      - name: Setup Poetry
        uses: moneymeets/action-setup-poetry@master

      - name: Restore virtualenv from Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Create virtualenv and install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Linter
        run: poetry run flake8

      - name: Test
        run: poetry run pytest

      - name: Check requirements
        run: |
          poetry export -f requirements.txt -o requirements-ci.txt
          diff -u requirements.txt requirements-ci.txt
