name: CI
on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python + Poetry
        uses: moneymeets/action-setup-python-poetry@master

      - name: Linter
        run: poetry run flake8

      - name: Test
        run: poetry run pytest

      - name: Check requirements
        run: |
          poetry export -f requirements.txt -o requirements-ci.txt
          diff -u requirements.txt requirements-ci.txt
