name: CI
on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python + Poetry
        uses: moneymeets/action-setup-python-poetry@master

      - name: Run linter
        uses: moneymeets/moneymeets-composite-actions/lint-python@master

      - name: Test
        run: poetry run pytest --cov --cov-fail-under=84
